Override transitive dependency
Override transitive dependency on spring-core 5.2.x, as otherwise we get
 a NoClassDefFoundError for ConcurrentLruCache which was introduced in
 spring-core 5.3.0

#55